### ISSUE TITLE
hive-context throws No such var: sql/hive-context

### ISSUE THREAD

**Issue by nightlord** [yieldbot/flambo#106]
lein uberjar 
(sql/hive-context sc) throws error,
but  (import '(org.apache.spark.sql.hive HiveContext))     (HiveContext. sc) is ok. 

project.clj
(defproject flambo-db "0.1.0"
  :description "FIXME: write description"
  :url "http://example.com/FIXME"
  :license {:name "Eclipse Public License"
            :url "http://www.eclipse.org/legal/epl-v10.html"}
  :dependencies [[org.clojure/clojure "1.8.0"]
                 [org.apache.spark/spark-hive_2.10 "1.6.1" :scope "provided"]
                 [org.apache.spark/spark-sql_2.10 "1.6.1" :scope "provided"]
                 [org.apache.spark/spark-core_2.10 "1.6.1" :scope "provided"]
                 [yieldbot/flambo "0.7.2"]]
  :aot [flambo-db.core]
  :profiles {:uberjar {:at all}
             :dev {:aot :all}})

(ns flambo-db.core
 (:require [flambo.api :as f]
           [flambo.conf :as conf]
           [flambo.tuple :as ft]
           [flambo.sql :as sql])
(:gen-class))

core.clj
(defn make-spark-context []
  (let [c (-> (conf/spark-conf)
              (conf/master (or (System/getenv "SPARK_MASTER") "yarn-client"))
              (conf/set "spark.sql.hive.version" "1.2.1")
              (conf/app-name (or (System/getenv "APP_NAME") "security-lab")))]
    (f/spark-context c)))

(defn -main [& args]
  (let [sc (make-spark-context)
      c  (sql/hive-context sc)
      data (.sql c "show databases")]
  (.show data)))

Compiling flambo-db.core
Reflection warning, flambo/function.clj:28:21 - reference to field state can't be resolved.
java.lang.RuntimeException: No such var: sql/hive-context, compiling:(flambo_db/core.clj:17:10)
Exception in thread "main" java.lang.RuntimeException: No such var: sql/hive-context, compiling:(flambo_db/core.clj:17:10)
	at clojure.lang.Compiler.analyze(Compiler.java:6688)
	at clojure.lang.Compiler.analyze(Compiler.java:6625)
	at clojure.lang.Compiler$InvokeExpr.parse(Compiler.java:3766)
	at clojure.lang.Compiler.analyzeSeq(Compiler.java:6870)
	at clojure.lang.Compiler.analyze(Compiler.java:6669)
	at clojure.lang.Compiler.access$300(Compiler.java:38)
	at clojure.lang.Compiler$LetExpr$Parser.parse(Compiler.java:6269)
	at clojure.lang.Compiler.analyzeSeq(Compiler.java:6868)
	at clojure.lang.Compiler.analyze(Compiler.java:6669)
	at clojure.lang.Compiler.analyzeSeq(Compiler.java:6856)
	at clojure.lang.Compiler.analyze(Compiler.java:6669)
	at clojure.lang.Compiler.analyze(Compiler.java:6625)
	at clojure.lang.Compiler$BodyExpr$Parser.parse(Compiler.java:6001)
	at clojure.lang.Compiler$FnMethod.parse(Compiler.java:5380)
	at clojure.lang.Compiler$FnExpr.parse(Compiler.java:3972)
	at clojure.lang.Compiler.analyzeSeq(Compiler.java:6866)
	at clojure.lang.Compiler.analyze(Compiler.java:6669)
	at clojure.lang.Compiler.analyzeSeq(Compiler.java:6856)
	at clojure.lang.Compiler.analyze(Compiler.java:6669)
	at clojure.lang.Compiler.access$300(Compiler.java:38)
	at clojure.lang.Compiler$DefExpr$Parser.parse(Compiler.java:589)
	at clojure.lang.Compiler.analyzeSeq(Compiler.java:6868)
	at clojure.lang.Compiler.analyze(Compiler.java:6669)
	at clojure.lang.Compiler.analyze(Compiler.java:6625)
	at clojure.lang.Compiler.compile1(Compiler.java:7469)
	at clojure.lang.Compiler.compile(Compiler.java:7541)
	at clojure.lang.RT.compile(RT.java:406)
	at clojure.lang.RT.load(RT.java:451)
	at clojure.lang.RT.load(RT.java:419)
	at clojure.core$load$fn__5677.invoke(core.clj:5893)
	at clojure.core$load.invokeStatic(core.clj:5892)
	at clojure.core$load.doInvoke(core.clj:5876)
	at clojure.lang.RestFn.invoke(RestFn.java:408)
	at clojure.core$load_one.invokeStatic(core.clj:5697)
	at clojure.core$compile$fn__5682.invoke(core.clj:5903)
	at clojure.core$compile.invokeStatic(core.clj:5903)
	at clojure.core$compile.invoke(core.clj:5895)
	at user$eval20$fn__29.invoke(form-init781755364739268990.clj:1)
	at user$eval20.invokeStatic(form-init781755364739268990.clj:1)
	at user$eval20.invoke(form-init781755364739268990.clj:1)
	at clojure.lang.Compiler.eval(Compiler.java:6927)
	at clojure.lang.Compiler.eval(Compiler.java:6917)
	at clojure.lang.Compiler.eval(Compiler.java:6917)
	at clojure.lang.Compiler.load(Compiler.java:7379)
	at clojure.lang.Compiler.loadFile(Compiler.java:7317)
	at clojure.main$load_script.invokeStatic(main.clj:275)
	at clojure.main$init_opt.invokeStatic(main.clj:277)
	at clojure.main$init_opt.invoke(main.clj:277)
	at clojure.main$initialize.invokeStatic(main.clj:308)
	at clojure.main$null_opt.invokeStatic(main.clj:342)
	at clojure.main$null_opt.invoke(main.clj:339)
	at clojure.main$main.invokeStatic(main.clj:421)
	at clojure.main$main.doInvoke(main.clj:384)
	at clojure.lang.RestFn.invoke(RestFn.java:421)
	at clojure.lang.Var.invoke(Var.java:383)
	at clojure.lang.AFn.applyToHelper(AFn.java:156)
	at clojure.lang.Var.applyTo(Var.java:700)
	at clojure.main.main(main.java:37)
Caused by: java.lang.RuntimeException: No such var: sql/hive-context
	at clojure.lang.Util.runtimeException(Util.java:221)
	at clojure.lang.Compiler.resolveIn(Compiler.java:7138)
	at clojure.lang.Compiler.resolve(Compiler.java:7108)
	at clojure.lang.Compiler.analyzeSymbol(Compiler.java:7069)
	at clojure.lang.Compiler.analyze(Compiler.java:6648)
	... 57 more

**Comment by sorenmacbeth** [comment]
`sql/hive-context` was not added until after 0.7.2 as you can see here:

https://github.com/yieldbot/flambo/blob/0.7.2/src/clojure/flambo/sql.clj
