### ISSUE TITLE
No matching method found: reduceByKey

### ISSUE THREAD

**Issue by afandian** [yieldbot/flambo#47]
Code that was working previously has stopped working with 0.5.0-SNAPSHOT.

    (f/reduce-by-key
      (f/map collection (f/fn [[k _]] [k 1]))
      (f/fn [a b] (+ a b)))

    Exception in thread "main" java.lang.IllegalArgumentException: No matching method found: reduceByKey for class org.apache.spark.api.java.JavaRDD
      at clojure.lang.Reflector.invokeMatchingMethod(Reflector.java:53)
      at clojure.lang.Reflector.invokeInstanceMethod(Reflector.java:28)
      at flambo.api$reduce_by_key.invoke(api.clj:249)

Versions:

[yieldbot/flambo "0.5.0-SNAPSHOT"]
[org.apache.spark/spark-core_2.10 "1.2.1"]

Any ideas?

**Comment by sorenmacbeth** [comment]
Yes. 0.5.0 has breaking changes around handling of `JavaPairRDD`. there is some more info here:

https://groups.google.com/d/msg/flambo-user/ovU4k1synKI/2MnMw7Dw71EJ

Another place to look is the updated tests and the example topology.

**Comment by afandian** [comment]
Ah right, thanks very much.
