### ISSUE TITLE
Flambo on Mesos

### ISSUE THREAD

**Issue by hellonico** [yieldbot/flambo#70]
Hi there, 

Enjoying Flambo quite a bit.
I am trying to move stuff to mesos, got the following code:

```clojure
    (def conf-messos (->
                        (conf/spark-conf)
                        (conf/set "spark.mesos.executor.home" "../../Downloads/spark-1.4.0-bin-hadoop2.4")
                        (conf/set "spark.serializer", "org.apache.spark.serializer.KryoSerializer")
                        (conf/master "mesos://172.16.2.8:5050")
                        (conf/app-name "mesos-test")))

      (f/with-context c conf-messos
       (-> (f/parallelize sc [1 2 3 4 5 6])
                (f/map (f/fn [x] (* 2 x)))
                f/collect
                vec))
```

And keep on bumping in the following:

```
15/07/03 19:09:19 WARN fn: caught exception: com.esotericsoftware.kryo.KryoException: java.util.ConcurrentModificationException
Serialization trace:
classes (sun.misc.Launcher$AppClassLoader)
classloader (java.security.ProtectionDomain)
context (java.security.AccessControlContext)
acc (clojure.lang.DynamicClassLoader)
classLoader (akka.actor.ReflectiveDynamicAccess)
_pm (akka.actor.ActorSystemImpl)
actorSystem (org.apache.spark.SparkEnv)
env (org.apache.spark.api.java.JavaSparkContext)
15/07/03 19:09:19 WARN fn: unable to call serializable.fn$serialize@31f35c90 on org.apache.spark.api.java.JavaSparkContext@6adfdaa3 in {"c" #object[org.apache.spark.api.java.JavaSparkContext 0x6adfdaa3 "org.apache.spark.api.java.JavaSparkContext@6adfdaa3"]}
```

and then a bit later:

```
15/07/03 19:09:19 WARN TaskSetManager: Lost task 1.0 in stage 2.0 (TID 17, slave1): java.lang.IllegalStateException: unread block data
	at java.io.ObjectInputStream$BlockDataInputStream.setBlockDataMode(ObjectInputStream.java:2424)
	at java.io.ObjectInputStream.readObject0(ObjectInputStream.java:1383)
	at java.io.ObjectInputStream.defaultReadFields(ObjectInputStream.java:1993)
	at java.io.ObjectInputStream.readSerialData(ObjectInputStream.java:1918)
	at java.io.ObjectInputStream.readOrdinaryObject(ObjectInputStream.java:1801)
	at java.io.ObjectInputStream.readObject0(ObjectInputStream.java:1351)
	at java.io.ObjectInputStream.readObject(ObjectInputStream.java:371)
	at org.apache.spark.serializer.JavaDeserializationStream.readObject(JavaSerializer.scala:69)
	at org.apache.spark.serializer.JavaSerializerInstance.deserialize(JavaSerializer.scala:95)
	at org.apache.spark.executor.Executor$TaskRunner.run(Executor.scala:194)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
```

Any idea where to start looking ? or debugging ?

**Comment by sorenmacbeth** [comment]
Again,

There are just warnings. You can safely ignore them as long as your code completes as you expect and/or you don't get any runtimeexpections or other ERROR level ones that stop execution.
