### ISSUE TITLE
Running on mesos with lein run

### ISSUE THREAD

**Issue by krukowski** [yieldbot/flambo#74]
I've been trying to run the tfidf example on mesos and have been running into issues when doing so through lein, throwing this error:
```
Exception in thread "Thread-29" java.lang.NoSuchMethodError: org.apache.mesos.Protos$ExecutorInfo$Builder.setData(Lorg/apache/mesos/protobuf/ByteString;)Lorg/apache/mesos/Protos$ExecutorInfo$Builder;
	at org.apache.spark.scheduler.cluster.mesos.MesosSchedulerBackend.createExecutorInfo(MesosSchedulerBackend.scala:130)
	at org.apache.spark.scheduler.cluster.mesos.MesosSchedulerBackend.createMesosTask(MesosSchedulerBackend.scala:270)
	at org.apache.spark.scheduler.cluster.mesos.MesosSchedulerBackend$$anonfun$resourceOffers$1$$anonfun$apply$mcV$sp$2$$anonfun$apply$1.apply(MesosSchedulerBackend.scala:232)
	at org.apache.spark.scheduler.cluster.mesos.MesosSchedulerBackend$$anonfun$resourceOffers$1$$anonfun$apply$mcV$sp$2$$anonfun$apply$1.apply(MesosSchedulerBackend.scala:226)
	at scala.collection.mutable.ResizableArray$class.foreach(ResizableArray.scala:59)
	at scala.collection.mutable.ArrayBuffer.foreach(ArrayBuffer.scala:47)
	at org.apache.spark.scheduler.cluster.mesos.MesosSchedulerBackend$$anonfun$resourceOffers$1$$anonfun$apply$mcV$sp$2.apply(MesosSchedulerBackend.scala:226)
	at org.apache.spark.scheduler.cluster.mesos.MesosSchedulerBackend$$anonfun$resourceOffers$1$$anonfun$apply$mcV$sp$2.apply(MesosSchedulerBackend.scala:225)
	at scala.collection.mutable.ResizableArray$class.foreach(ResizableArray.scala:59)
	at scala.collection.mutable.ArrayBuffer.foreach(ArrayBuffer.scala:47)
	at org.apache.spark.scheduler.cluster.mesos.MesosSchedulerBackend$$anonfun$resourceOffers$1.apply$mcV$sp(MesosSchedulerBackend.scala:225)
	at org.apache.spark.scheduler.cluster.mesos.MesosSchedulerBackend.inClassLoader(MesosSchedulerBackend.scala:172)
	at org.apache.spark.scheduler.cluster.mesos.MesosSchedulerBackend.resourceOffers(MesosSchedulerBackend.scala:188)
```

For context, it works when running the example exactly as is with master set to `local[*]`, and also when I send the uberjar to mesos using spark-submit. The only change from the example code is changing `master` to point to the mesos master, and adding a `spark.mesos.executor.home` to the conf.

Any ideas what might be going wrong?

**Comment by sorenmacbeth** [comment]
Looks to me like you've got a classpath/dependency issue. Possibly multiple versions of protobuf. 

This isn't specific to flambo, so I'm going to close this issue.

**Comment by krukowski** [comment]
Oh, I think you might be right. Sorry and thanks for the help!
