### ISSUE TITLE
Flambo Stand-Alone Applications Broken

### ISSUE THREAD

**Issue by senor-hadoop** [yieldbot/flambo#78]
Flambo applications run in stand-alone mode, whether in YARN(--master yarn-cluster, --master yarn-client), stand-alone cluster (--master spark://...) or locally (--master local[*]), all fail with the nearly the same stacktrace found below. Essentially, nothing with 'spark-submit' works. For those wanting to try YARN mode, an out-of-the-box YARN cluster can be found within the Hortonworks sandbox (a virtual machine): http://hortonworks.com/products/hortonworks-sandbox/

SLF4J: Class path contains multiple SLF4J bindings.
SLF4J: Found binding in [jar:file:/hadoop/yarn/local/usercache/snunez/filecache/10/spark-assembly-1.2.1.2.2.4.2-2-hadoop2.6.0.2.2.4.2-2.jar!/org/slf4j/impl/StaticLoggerBinder.class]
SLF4J: Found binding in [jar:file:/usr/hdp/2.2.4.2-2/hadoop/lib/slf4j-log4j12-1.7.5.jar!/org/slf4j/impl/StaticLoggerBinder.class]
SLF4J: See http://www.slf4j.org/codes.html#multiple_bindings for an explanation.
SLF4J: Actual binding is of type [org.slf4j.impl.Log4jLoggerFactory]
15/07/25 03:05:38 INFO yarn.ApplicationMaster: Registered signal handlers for [TERM, HUP, INT]
15/07/25 03:05:39 INFO yarn.ApplicationMaster: ApplicationAttemptId: appattempt_1437781501203_0001_000001
15/07/25 03:05:40 INFO spark.SecurityManager: Changing view acls to: yarn,snunez
15/07/25 03:05:40 INFO spark.SecurityManager: Changing modify acls to: yarn,snunez
15/07/25 03:05:40 INFO spark.SecurityManager: SecurityManager: authentication disabled; ui acls disabled; users with view permissions: Set(yarn, snunez); users with modify permissions: Set(yarn, snunez)
15/07/25 03:05:40 INFO yarn.ApplicationMaster: Starting the user JAR in a separate Thread
15/07/25 03:05:40 INFO yarn.ApplicationMaster: Waiting for spark context initialization
15/07/25 03:05:40 INFO yarn.ApplicationMaster: Waiting for spark context initialization ... 0
Exception in thread "Driver" java.lang.ExceptionInInitializerError
	at java.lang.Class.forName0(Native Method)
	at java.lang.Class.forName(Class.java:278)
	at clojure.lang.RT.loadClassForName(RT.java:2093)
	at clojure.lang.RT.load(RT.java:430)
	at clojure.lang.RT.load(RT.java:411)
	at clojure.core$load$fn__5066.invoke(core.clj:5641)
	at clojure.core$load.doInvoke(core.clj:5640)
	at clojure.lang.RestFn.invoke(RestFn.java:408)
	at clojure.core$load_one.invoke(core.clj:5446)
	at clojure.core$load_lib$fn__5015.invoke(core.clj:5486)
	at clojure.core$load_lib.doInvoke(core.clj:5485)
	at clojure.lang.RestFn.applyTo(RestFn.java:142)
	at clojure.core$apply.invoke(core.clj:626)
	at clojure.core$load_libs.doInvoke(core.clj:5524)
	at clojure.lang.RestFn.applyTo(RestFn.java:137)
	at clojure.core$apply.invoke(core.clj:626)
	at clojure.core$require.doInvoke(core.clj:5607)
	at clojure.lang.RestFn.invoke(RestFn.java:551)
	at flambo.api$loading__4958__auto__.invoke(api.clj:12)
	at flambo.api__init.load(Unknown Source)
	at flambo.api__init.<clinit>(Unknown Source)
	at java.lang.Class.forName0(Native Method)
	at java.lang.Class.forName(Class.java:278)
	at clojure.lang.RT.loadClassForName(RT.java:2093)
	at clojure.lang.RT.load(RT.java:430)
	at clojure.lang.RT.load(RT.java:411)
	at clojure.core$load$fn__5066.invoke(core.clj:5641)
	at clojure.core$load.doInvoke(core.clj:5640)
	at clojure.lang.RestFn.invoke(RestFn.java:408)
	at clojure.core$load_one.invoke(core.clj:5446)
	at clojure.core$load_lib$fn__5015.invoke(core.clj:5486)
	at clojure.core$load_lib.doInvoke(core.clj:5485)
	at clojure.lang.RestFn.applyTo(RestFn.java:142)
	at clojure.core$apply.invoke(core.clj:626)
	at clojure.core$load_libs.doInvoke(core.clj:5524)
	at clojure.lang.RestFn.applyTo(RestFn.java:137)
	at clojure.core$apply.invoke(core.clj:626)
	at clojure.core$require.doInvoke(core.clj:5607)
	at clojure.lang.RestFn.invoke(RestFn.java:512)
	at ict.core$loading__4958__auto__.invoke(core.clj:1)
	at ict.core__init.load(Unknown Source)
	at ict.core__init.<clinit>(Unknown Source)
	at java.lang.Class.forName0(Native Method)
	at java.lang.Class.forName(Class.java:278)
	at clojure.lang.RT.loadClassForName(RT.java:2093)
	at clojure.lang.RT.load(RT.java:430)
	at clojure.lang.RT.load(RT.java:411)
	at clojure.core$load$fn__5066.invoke(core.clj:5641)
	at clojure.core$load.doInvoke(core.clj:5640)
	at clojure.lang.RestFn.invoke(RestFn.java:408)
	at clojure.lang.Var.invoke(Var.java:379)
	at ict.core.<clinit>(Unknown Source)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:606)
	at org.apache.spark.deploy.yarn.ApplicationMaster$$anon$2.run(ApplicationMaster.scala:445)
Caused by: java.lang.ClassNotFoundException: flambo.WriterOutputStream
	at java.net.URLClassLoader$1.run(URLClassLoader.java:366)
	at java.net.URLClassLoader$1.run(URLClassLoader.java:355)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.net.URLClassLoader.findClass(URLClassLoader.java:354)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:425)
	at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:308)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:358)
	at java.lang.Class.forName0(Native Method)
	at java.lang.Class.forName(Class.java:195)
	at flambo.utils$loading__4958__auto__.invoke(utils.clj:1)
	at flambo.utils__init.load(Unknown Source)
	at flambo.utils__init.<clinit>(Unknown Source)
	... 57 more

**Comment by sorenmacbeth** [comment]
I've not tried YARN, but spark standalone and mesos via spark-submit absolutely do work. We launch all our flambo application via spark submit into a mesos/spark cluster.

**Comment by senor-hadoop** [comment]
OK, so that is the one combination I didn't try because I don't have a mesos/spark cluster. Are you running the current branch from github?


In any event, they are failing in all modes, for me, running the latest from 'develop'. Any thoughts on how to begin debugging this? The REPL works fine, but standalone blows up with:


Caused by: java.lang.ClassNotFoundException: flambo.WriterOutputStream
    at java.net.URLClassLoader$1.run(URLClassLoader.java:366)
    at java.net.URLClassLoader$1.run(URLClassLoader.java:355)
    at java.security.AccessController.doPrivileged(Native Method)
    at java.net.URLClassLoader.findClass(URLClassLoader.java:354)
    at java.lang.ClassLoader.loadClass(ClassLoader.java:425)
    at java.lang.ClassLoader.loadClass(ClassLoader.java:358)
    at java.lang.Class.forName0(Native Method)
    at java.lang.Class.forName(Class.java:195)
    at flambo.utils$loading__4958__auto__.invoke(utils.clj:1)
    at flambo.utils__init.load(Unknown Source)
    at flambo.utils__init.<clinit>(Unknown Source)







________________________________

**Comment by sorenmacbeth** [comment]
Can you unzip your uberjar and verify that flambo/WriterOutputStream.class exists in it?

**Comment by sorenmacbeth** [comment]
Also, try passing clojure.main as your --class to spark-submit. This should start up a repl. In that repl try (import flambo.WriterOutputStream) and see what happens.

**Comment by senor-hadoop** [comment]
Interesting. The class is not in the uberjar file, and when I try it at the REPL:


user=> (import flambo.WriterOutputStream)
ClassNotFoundException flambo.WriterOutputStream  java.net.URLClassLoader$1.run (URLClassLoader.java:366)


yet it is in the flambo source and JAR:


[snunez@sandbox flambo]$ fgrep -R WriterOutputStream *
src/clojure/flambo/utils.clj:           [flambo WriterOutputStream]
src/clojure/flambo/utils.clj:  (System/setOut (PrintStream. (WriterOutputStream. *out*))))
src/java/flambo/WriterOutputStream.java:public class WriterOutputStream extends OutputStream {
src/java/flambo/WriterOutputStream.java:  public WriterOutputStream(Writer writer) {
Binary file target/classes/flambo/WriterOutputStream.class matches
Binary file target/flambo-0.7.0-SNAPSHOT.jar matches


?




________________________________

**Comment by sorenmacbeth** [comment]
I took a second look at your project.clj from the mailing list thread and now (less tired) there a couple of oddities:

```clojure
(defproject ict "0.1.0-SNAPSHOT"
  :description "Transform ICT files to Hive"
  :resource-paths ["/usr/local/src/flambo/target/flambo-0.7.0-SNAPSHOT.jar"] ; We're both developing and using flambo
  :url "http://hortonworks.com"
  :license {:name "Eclipse Public License"
            :url "http://www.eclipse.org/legal/epl-v10.html"}
  :dependencies [[org.clojure/clojure "1.6.0"]
                 [org.clojure/core.memoize "0.5.7"]
                 [yieldbot/serializable-fn "0.0.9"
                  :exclusions [com.twitter/chill-java]]  ; Normally not need except when compiling flambo locally
                 [clj-time "0.10.0"]]
  :plugins [[cider/cider-nrepl "0.10.0-SNAPSHOT"]] ; Need this because of cider/lein strangeness
  :target-path "target/%s"
  :profiles {:dev
             ;; so gen-class stuff works in the repl
             {:aot [flambo.function ict.core]}
             :provided
             {:dependencies
              [[org.apache.spark/spark-core_2.10 "1.3.1"]
               [org.apache.spark/spark-streaming_2.10 "1.3.1"]
               [org.apache.spark/spark-streaming-kafka_2.10 "1.3.1"]
               [org.apache.spark/spark-streaming-flume_2.10 "1.3.1"]
               [org.apache.spark/spark-sql_2.10 "1.3.1"]
               [org.clojure/tools.nrepl "0.2.7"]]}
             :uberjar
             {:aot :all}})
```

why are you putting flambo in `:resource-paths`? I don't believe it will be included in the uberjar this way. You need to declare it under `:dependencies`. Specifying your `:target-path` is not usually necessary. I don't think it would cause a problem, but I'd just remove it unless you changing it from the default for some special reason.

**Comment by senor-hadoop** [comment]
The target-path isn't necessary; just something left from an experiment and, as you point out, not causing any harm.


I had resource-paths in there because I want to pull in my version of Flambo, rather than something from clojars (based off this StackOverflow post<http://stackoverflow.com/questions/2404426/leiningen-how-to-add-dependencies-for-local-jars>), although on rereading that post I see there is a note that it doesn't work with uberjars.

I'd like to keep it as simple as possible, and many of the suggestions I've found involve maintaining local maven repos and such.


Can anyone using a local copy of Flambo to develop projects post their project.clj file? It would be a useful thing to inspect.


    - Steve


________________________________

**Comment by sorenmacbeth** [comment]
I edited my previous comment to include info on leiningen checkouts, which
will do exactly what you want.

**Comment by senor-hadoop** [comment]
Thanks. I've tried that, but lein gets into an infinite loop, producing an uberjar of ever increasing size. There is also a clean solution in the StackOverflow post:



I find lein pom; lein jar; lein install works well when developing libraries.

Do this in the library being developed and your application requiring it will use it without any :repositories foo required.

________________________________

Alternatively, lein do pom, jar, install is slightly more concise.

________________________________

This allows calling the library like any other :dependencies [[project-name "version"]]



Compared to the other solutions this is so simple and it works! No need to install maven. Thanks. –  dkinzer<http://stackoverflow.com/users/256854/dkinzer> Jul 28 '13 at 0:16<http://stackoverflow.com/questions/2404426/leiningen-how-to-add-dependencies-for-local-jars#comment26152207_13733562>



How do you reference the resulting jar in a lein project file? –  interstar<http://stackoverflow.com/users/8482/interstar> Sep 4 '14 at 7:46<http://stackoverflow.com/questions/2404426/leiningen-how-to-add-dependencies-for-local-jars#comment40097907_13733562>



Like any other :dependencies [[project-name "version"]] –  roboli<http://stackoverflow.com/users/2202143/roboli> Sep 4 '14 at 17:09<http://stackoverflow.com/questions/2404426/leiningen-how-to-add-dependencies-for-local-jars#comment40117906_13733562>



However that's not working either. Once I get things working I'll update the README.md to cover the use case of both developing Flambo and using it at the same time, which I imagine must be fairly common.


In the meantime though, I would love to see a working project.clj file that has this configuration. I can't be the only one doing this.




________________________________

**Comment by senor-hadoop** [comment]
I'm going to close this one, but not because I have any idea what's wrong. After more than half a day of trying to make 'checkout' work, I'm giving up because I have something that WFM (works for me). It would be a great addition to the documentation if someone smarter than I created a tutorial and examples for stand-alone Flambo applications.


To help anyone else in this situation, with an explanation as to why it works, this is what's in my project file:


(defproject ict "0.1.0-SNAPSHOT"
  :description "Transform ICT files to Hive"
  :resource-paths ["/usr/local/src/flambo/target/flambo-0.7.9-SNAPSHOT.jar"] ; We're both developing and using flambo
  :url "http://hortonworks.com"
  :license {:name "Eclipse Public License"
            :url "http://www.eclipse.org/legal/epl-v10.html"}
  :dependencies [[org.clojure/clojure "1.6.0"]
                 [yieldbot/flambo "0.7.1-SNAPSHOT"]
                 [clj-time "0.10.0"]]
  :plugins [[cider/cider-nrepl "0.10.0-SNAPSHOT"]] ; Need this because of cider/lein strangeness
  :profiles {:dev
             {:aot [flambo.function ict.core]}             ; so gen-class stuff works in the REPL
             :provided
             {:dependencies
              [[org.apache.spark/spark-core_2.10 "1.3.1"]
               [org.apache.spark/spark-streaming_2.10 "1.3.1"]
               [org.apache.spark/spark-streaming-kafka_2.10 "1.3.1"]
               [org.apache.spark/spark-streaming-flume_2.10 "1.3.1"]
               [org.apache.spark/spark-sql_2.10 "1.3.1"]
               [org.clojure/tools.nrepl "0.2.7"]]}
             :uberjar
             {:aot :all}})


Note that the ':resources-paths' must be present. This is odd, since it doesn't even have to point to the correct JAR (as above), but without that line leiningen seems to get itself into an infinite loop of sorts and the uberjar keeps growing until the system runs out of disk. By all documented accounts, there seems to be two ways of doing this:

  *   Using the 'checkouts' directory method mentioned by Soren
  *   Doing 'lein install' in the Flambo directory every time you make a change (which I think would be required anyway) and having a dependency line in project.clj

If anyone does figure this out, or has a working example, please post it to the group.



________________________________

**Comment by sorenmacbeth** [comment]
Just for my own edification, when you create the checkouts dir and symlink to your flambo repo, you are *also* adding flambo with the correct version to your `:dependencies` in your project.clj yes?

**Comment by sorenmacbeth** [comment]
fwiw, I am unable to replicate the ever-increasing uberjar issue using a checkouts dir as described in the link I provided above.

**Comment by senor-hadoop** [comment]
Yes, but it still doesn't work for me.


________________________________

**Comment by senor-hadoop** [comment]
Problem solved.


The reason the :resources was required, even though it pointed to nonsense, was because it excluded the 'real' resources directory. I had placed my training data in that directory, and there is a lot of it. Enough so that duplicating it in the JAR file filled up the disk. Moral of the story: put training data in test, even though it conceptually (to me anyway) belongs in resources.




________________________________
