### ISSUE TITLE
0.8.0-SNAPSHOT failed with java.lang.ClassCastException: clojure.lang.LazySeq 

### ISSUE THREAD

**Issue by tokomakoma123** [yieldbot/flambo#97]
The following code works on spark 1.6.1(flambo 0.7.2-SNAPSHOT) but does not work on spark 2.0(flambo 0.8.0-SNAPSHOT).

```clj
(ns spark-example.core
  (:require [flambo.conf :as conf]
            [flambo.api :as f]))

(def c (-> (conf/spark-conf)
           (conf/master "local[3]")
           (conf/app-name "flambo-example")))

(def sc (f/spark-context c))

(-> (f/text-file sc "data/advs.txt")
    (f/flat-map
     (f/fn [line]
       (map str/lower-case
            (remove #(= % "")(str/split line #"[^a-zA-Z]+")))))
    (f/map-to-pair (f/fn [w] (ft/tuple w 1)))
    (f/reduce-by-key (f/fn [x y] (+ x y)))
    f/sort-by-key
    (f/take 10))
```
The stacktrace as follows:

```
2. Unhandled org.apache.spark.SparkException
   Job aborted due to stage failure: Task 0 in stage 0.0 failed 1
   times, most recent failure: Lost task 0.0 in stage 0.0 (TID 0,
   localhost): java.lang.ClassCastException: clojure.lang.LazySeq
   cannot be cast to java.util.Iterator at
   flambo.function.FlatMapFunction.call(Unknown Source) at
   org.apache.spark.api.java.JavaRDDLike$$anonfun$fn$1$1.apply(JavaRDDLike.scala:124)
   at
   org.apache.spark.api.java.JavaRDDLike$$anonfun$fn$1$1.apply(JavaRDDLike.scala:124)
   at scala.collection.Iterator$$anon$12.nextCur(Iterator.scala:434)
   at scala.collection.Iterator$$anon$12.hasNext(Iterator.scala:440)
   at scala.collection.Iterator$$anon$11.hasNext(Iterator.scala:408)
   at
   org.apache.spark.util.collection.ExternalSorter.insertAll(ExternalSorter.scala:192)
   at
   org.apache.spark.shuffle.sort.SortShuffleWriter.write(SortShuffleWriter.scala:63)
   at
   org.apache.spark.scheduler.ShuffleMapTask.runTask(ShuffleMapTask.scala:79)
   at
   org.apache.spark.scheduler.ShuffleMapTask.runTask(ShuffleMapTask.scala:47)
   at org.apache.spark.scheduler.Task.run(Task.scala:85) at
   org.apache.spark.executor.Executor$TaskRunner.run(Executor.scala:274)
   at
   java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
   at
   java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
   at java.lang.Thread.run(Thread.java:745)
   
   Driver stacktrace:

        DAGScheduler.scala: 1450  org.apache.spark.scheduler.DAGScheduler/org$apache$spark$scheduler$DAGScheduler$$failJobAndIndependentStages
        DAGScheduler.scala: 1438  org.apache.spark.scheduler.DAGScheduler$$anonfun$abortStage$1/apply
        DAGScheduler.scala: 1437  org.apache.spark.scheduler.DAGScheduler$$anonfun$abortStage$1/apply
      ResizableArray.scala:   59  scala.collection.mutable.ResizableArray$class/foreach
         ArrayBuffer.scala:   48  scala.collection.mutable.ArrayBuffer/foreach
        DAGScheduler.scala: 1437  org.apache.spark.scheduler.DAGScheduler/abortStage
        DAGScheduler.scala:  811  org.apache.spark.scheduler.DAGScheduler$$anonfun$handleTaskSetFailed$1/apply
        DAGScheduler.scala:  811  org.apache.spark.scheduler.DAGScheduler$$anonfun$handleTaskSetFailed$1/apply
              Option.scala:  257  scala.Option/foreach
        DAGScheduler.scala:  811  org.apache.spark.scheduler.DAGScheduler/handleTaskSetFailed
        DAGScheduler.scala: 1659  org.apache.spark.scheduler.DAGSchedulerEventProcessLoop/doOnReceive
        DAGScheduler.scala: 1618  org.apache.spark.scheduler.DAGSchedulerEventProcessLoop/onReceive
        DAGScheduler.scala: 1607  org.apache.spark.scheduler.DAGSchedulerEventProcessLoop/onReceive
           EventLoop.scala:   48  org.apache.spark.util.EventLoop$$anon$1/run
        DAGScheduler.scala:  632  org.apache.spark.scheduler.DAGScheduler/runJob
        SparkContext.scala: 1871  org.apache.spark.SparkContext/runJob
        SparkContext.scala: 1884  org.apache.spark.SparkContext/runJob
        SparkContext.scala: 1897  org.apache.spark.SparkContext/runJob
        SparkContext.scala: 1911  org.apache.spark.SparkContext/runJob
                 RDD.scala:  893  org.apache.spark.rdd.RDD$$anonfun$collect$1/apply
   RDDOperationScope.scala:  151  org.apache.spark.rdd.RDDOperationScope$/withScope
   RDDOperationScope.scala:  112  org.apache.spark.rdd.RDDOperationScope$/withScope
                 RDD.scala:  358  org.apache.spark.rdd.RDD/withScope
                 RDD.scala:  892  org.apache.spark.rdd.RDD/collect
         Partitioner.scala:  264  org.apache.spark.RangePartitioner$/sketch
         Partitioner.scala:  126  org.apache.spark.RangePartitioner/<init>
 OrderedRDDFunctions.scala:   62  org.apache.spark.rdd.OrderedRDDFunctions$$anonfun$sortByKey$1/apply
 OrderedRDDFunctions.scala:   61  org.apache.spark.rdd.OrderedRDDFunctions$$anonfun$sortByKey$1/apply
   RDDOperationScope.scala:  151  org.apache.spark.rdd.RDDOperationScope$/withScope
   RDDOperationScope.scala:  112  org.apache.spark.rdd.RDDOperationScope$/withScope
                 RDD.scala:  358  org.apache.spark.rdd.RDD/withScope
 OrderedRDDFunctions.scala:   61  org.apache.spark.rdd.OrderedRDDFunctions/sortByKey
         JavaPairRDD.scala:  913  org.apache.spark.api.java.JavaPairRDD/sortByKey
NativeMethodAccessorImpl.java:   -2  sun.reflect.NativeMethodAccessorImpl/invoke0
NativeMethodAccessorImpl.java:   62  sun.reflect.NativeMethodAccessorImpl/invoke
DelegatingMethodAccessorImpl.java:   43  sun.reflect.DelegatingMethodAccessorImpl/invoke
               Method.java:  498  java.lang.reflect.Method/invoke
            Reflector.java:   93  clojure.lang.Reflector/invokeMatchingMethod
            Reflector.java:   28  clojure.lang.Reflector/invokeInstanceMethod
                   api.clj:  334  flambo.api/sort-by-key
                   api.clj:  319  flambo.api/sort-by-key
                   api.clj:  324  flambo.api/sort-by-key
                   api.clj:  319  flambo.api/sort-by-key
                      REPL:   61  spark-example.core/eval20572
                      REPL:   53  spark-example.core/eval20572
             Compiler.java: 6927  clojure.lang.Compiler/eval
             Compiler.java: 6890  clojure.lang.Compiler/eval
                  core.clj: 3105  clojure.core/eval
                  core.clj: 3101  clojure.core/eval
                  main.clj:  240  clojure.main/repl/read-eval-print/fn
                  main.clj:  240  clojure.main/repl/read-eval-print
                  main.clj:  258  clojure.main/repl/fn
                  main.clj:  258  clojure.main/repl
                  main.clj:  174  clojure.main/repl
               RestFn.java:  137  clojure.lang.RestFn/applyTo
                  core.clj:  646  clojure.core/apply
                  core.clj:  641  clojure.core/apply
                regrow.clj:   18  refactor-nrepl.ns.slam.hound.regrow/wrap-clojure-repl/fn
               RestFn.java: 1523  clojure.lang.RestFn/invoke
    interruptible_eval.clj:   87  clojure.tools.nrepl.middleware.interruptible-eval/evaluate/fn
                  AFn.java:  152  clojure.lang.AFn/applyToHelper
                  AFn.java:  144  clojure.lang.AFn/applyTo
                  core.clj:  646  clojure.core/apply
                  core.clj: 1881  clojure.core/with-bindings*
                  core.clj: 1881  clojure.core/with-bindings*
               RestFn.java:  425  clojure.lang.RestFn/invoke
    interruptible_eval.clj:   85  clojure.tools.nrepl.middleware.interruptible-eval/evaluate
    interruptible_eval.clj:   55  clojure.tools.nrepl.middleware.interruptible-eval/evaluate
    interruptible_eval.clj:  222  clojure.tools.nrepl.middleware.interruptible-eval/interruptible-eval/fn/fn
    interruptible_eval.clj:  190  clojure.tools.nrepl.middleware.interruptible-eval/run-next/fn
                  AFn.java:   22  clojure.lang.AFn/run
   ThreadPoolExecutor.java: 1142  java.util.concurrent.ThreadPoolExecutor/runWorker
   ThreadPoolExecutor.java:  617  java.util.concurrent.ThreadPoolExecutor$Worker/run
               Thread.java:  745  java.lang.Thread/run

1. Caused by java.lang.ClassCastException
   clojure.lang.LazySeq cannot be cast to java.util.Iterator

                       nil:   -1  flambo.function.FlatMapFunction/call
         JavaRDDLike.scala:  124  org.apache.spark.api.java.JavaRDDLike$$anonfun$fn$1$1/apply
         JavaRDDLike.scala:  124  org.apache.spark.api.java.JavaRDDLike$$anonfun$fn$1$1/apply
            Iterator.scala:  434  scala.collection.Iterator$$anon$12/nextCur
            Iterator.scala:  440  scala.collection.Iterator$$anon$12/hasNext
            Iterator.scala:  408  scala.collection.Iterator$$anon$11/hasNext
      ExternalSorter.scala:  192  org.apache.spark.util.collection.ExternalSorter/insertAll
   SortShuffleWriter.scala:   63  org.apache.spark.shuffle.sort.SortShuffleWriter/write
      ShuffleMapTask.scala:   79  org.apache.spark.scheduler.ShuffleMapTask/runTask
      ShuffleMapTask.scala:   47  org.apache.spark.scheduler.ShuffleMapTask/runTask
                Task.scala:   85  org.apache.spark.scheduler.Task/run
            Executor.scala:  274  org.apache.spark.executor.Executor$TaskRunner/run
   ThreadPoolExecutor.java: 1142  java.util.concurrent.ThreadPoolExecutor/runWorker
   ThreadPoolExecutor.java:  617  java.util.concurrent.ThreadPoolExecutor$Worker/run
               Thread.java:  745  java.lang.Thread/run
```
What is wrong ?

**Comment by sorenmacbeth** [comment]
Howdy, this is because the expected return class changed from Spark 1.6 to Spark 2.0. `flat-map` now expects a `java.util.Iterator` rather than a java Iterable. see [here](https://spark.apache.org/releases/spark-release-2-0-0.html#removals-behavior-changes-and-deprecations) for details on the changes. 

you should wrap your return value in `.iterator` as the test for flat-map do https://github.com/yieldbot/flambo/blob/develop/test/flambo/api_test.clj#L118

**Comment by tokomakoma123** [comment]
Thank you ! It worked to add .iterator.
